name: Maven Package

on:
  workflow_dispatch:

jobs:
  maven-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Package Step
        run: mvn -B -U package
      - name: Archive JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Jar Artifacts
          path: '**/target/*.jar'
